FROM php:8.2-fpm

ARG WITH_MEMCACHED=false
ARG WITH_REDIS=false

ENV WITH_MEMCACHED=$WITH_MEMCACHED
ENV WITH_REDIS=$WITH_REDIS

RUN apt-get update \
    && apt-get install -y iputils-ping openssh-client git zip unzip mariadb-client vim \
    && docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli \
    && docker-php-ext-install iconv

RUN if [ "${WITH_MEMCACHED}" = "true" ] ; then \
    apt-get install -y libz-dev libmemcached-dev \
    && apt-get install -y memcached libmemcached-tools \
    && pecl install memcached \
    && docker-php-ext-enable memcached; \
fi ;

RUN if [ "${WITH_REDIS}" = "true" ] ; then \
    pecl install redis && docker-php-ext-enable redis; \
fi ;

RUN pecl install xdebug && docker-php-ext-enable xdebug

RUN mkdir /var/log/apiopenstudio

RUN ln -s /usr/local/bin/php /usr/bin/php
