FROM php:8.1-fpm

ARG WITH_XDEBUG=false
ENV WITH_XDEBUG=$WITH_XDEBUG

RUN apt-get update
RUN apt-get install -y iputils-ping
RUN apt-get install -y openssh-client
RUN docker-php-ext-install mysqli
RUN docker-php-ext-enable mysqli
#RUN apt-get install -y php8-common
RUN docker-php-ext-install iconv

COPY ./* /throwaway/

RUN if [ "${WITH_XDEBUG}" = "true" ] ; then \
    pecl install xdebug && docker-php-ext-enable xdebug; \
    cp /throwaway/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    cp /throwaway/error_reporting.ini /usr/local/etc/php/conf.d/error_reporting.ini; \
fi ;

RUN rm -Rf /throwaway
