FROM php:7.4-fpm

ARG WITH_XDEBUG=false
ARG WITH_MEMCACHED=false
ARG WITH_REDIS=false

ENV WITH_XDEBUG=$WITH_XDEBUG
ENV WITH_MEMCACHED=$WITH_MEMCACHED
ENV WITH_REDIS=$WITH_REDIS

RUN apt-get update \
    && apt-get install -y iputils-ping openssh-client git zip unzip \
    && docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli

RUN if [ "${WITH_MEMCACHED}" = "true" ] ; then \
    apt-get install -y libz-dev libmemcached-dev \
    && apt-get install -y memcached libmemcached-tools \
    && pecl install memcached \
    && docker-php-ext-enable memcached; \
fi ;

RUN if [ "${WITH_REDIS}" = "true" ] ; then \
    pecl install redis && docker-php-ext-enable redis; \
fi ;

COPY ./* /throwaway/

RUN if [ "${WITH_XDEBUG}" = "true" ] ; then \
    pecl install xdebug && docker-php-ext-enable xdebug; \
    cp /throwaway/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    cp /throwaway/error_reporting.ini /usr/local/etc/php/conf.d/error_reporting.ini; \
fi ;

RUN rm -Rf /throwaway
